export const ActionTypes = {
    USER_LOGIN_SUCCESS:'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILURE:'USER_LOGIN_FAILURE',
    USER_SIGNUP:'USER_SIGNUP',
    USER_SIGNUP_SUCCESS:'USER_SIGNUP_SUCCESS',
    USER_SIGNUP_FAILURE:'USER_SIGNUP_FAILURE',
    USER_LOGOUT:'USER_LOGOUT',
    USER_LOGOUT_FAILURE:'USER_LOGOUT_FAILURE',
    ALL_COURSES:'ALL_COURSES',
    SIDEBAR: 'SIDEBAR',
    GET_ROLE: 'GET_ROLE'
}