export const ActionTypes = {
    USER_LOGIN:'USER_LOGIN',
    USER_LOGIN_SUCCESS:'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILURE:'USER_LOGIN_FAILURE',
    USER_SIGNUP:'USER_SIGNUP',
    USER_SIGNUP_SUCCESS:'USER_SIGNUP_SUCCESS',
    USER_FAILURE:'USER_SIGNUP_FAILURE',
}